services:
  kaggle:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: {{ project_name }}-cpu
    volumes:
      - ./input:/kaggle/input
      - .:/kaggle/working
      - ~/.kaggle:/root/.kaggle:ro
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/torch:/root/.cache/torch
      - ~/.cache/pip:/root/.cache/pip
      - ~/.cache/uv:/root/.cache/uv
      - ~/.netrc:/root/.netrc:ro
    environment:
      - PYTHONPATH=/kaggle/working
    working_dir: /kaggle/working
    ports:
      - "8889:8889"
    command: /bin/bash
    shm_size: "2gb"
    tty: true
    stdin_open: true
